version: '3.7'

services:
  client:
    image: unciornonacid/minion-client:develop
    build:
      context: docker/client
      dockerfile: Dockerfile
    ports:
      - 80:3000
    volumes:
      - ./client:/usr/src/client:rw

  api:
    image: unicornonacid/minion-api:develop
    build:
      context: docker/nginx
      dockerfile: ./Dockerfile
    depends_on:
      - php
    ports:
      - 8080:80
    volumes:
      - ./api/public:/srv/api/public:ro

  php:
    image: unicornonacid/minion-php:develop
    build:
      context: ./docker/php
      dockerfile: ./Dockerfile
    depends_on:
      - db
    volumes:
      - ./api:/srv/api:rw

  db:
    image: unicornonacid/minion-db:develop
    build:
      context: ./docker/db
      dockerfile: ./Dockerfile
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: S3eahub9vUh2YdSY
      API_USER: api
      API_PASSWORD: b5wZL3ECzCnEV7Hf
      POSTGRES_DB: minion
    ports:
      - 5432:5432
    volumes:
      - minion-data:/var/lib/postgresql/data:rw

volumes:
  minion-data: {}