version: '3.7'

services:
  php:
    image: unicornonacid/hamster-php:develop
    build:
      context: ./docker/php
      dockerfile: ./Dockerfile
    depends_on:
      - db
    volumes:
      - ./api:/srv/api:rw

  nginx:
    image: unicornonacid/hamster-nginx:develop
    build:
      context: docker/nginx
      dockerfile: ./Dockerfile
    depends_on:
      - php
    ports:
      - 8080:80
    volumes:
      - ./api/public:/srv/api/public:ro

  db:
    image: unicornonacid/hamster-db:develop
    build:
      context: ./docker/db
      dockerfile: ./Dockerfile
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: S3eahub9vUh2YdSY
      API_USER: api
      API_PASSWORD: b5wZL3ECzCnEV7Hf
      POSTGRES_DB: hamster
    ports:
      - 5432:5432
    volumes:
      - hamster-data:/var/lib/postgresql/data:rw

volumes:
  hamster-data: {}