version: '3.4'

services:
  php:
    build:
      context: ./docker/php
      dockerfile: ./Dockerfile
    depends_on:
      - db
    env_file:
      - ./api/.env
    volumes:
      - ./api:/srv/api:rw

  nginx:
    build:
      context: docker/nginx
      dockerfile: ./Dockerfile
    depends_on:
      - php
    ports:
      - 8080:80
    volumes:
      - ./api/public:/srv/api/public:ro

  db:
    build:
      context: ./docker/db
      dockerfile: ./Dockerfile
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: S3eahub9vUh2YdSY
      API_USER: api
      API_PASSWORD: b5wZL3ECzCnEV7Hf
      POSTGRES_DB: manager
    ports:
      - 5432:5432
    volumes:
      - money-manager-data:/var/lib/postgresql/data:rw

volumes:
  money-manager-data: {}